name: Call fetch workflow

on:
    workflow_dispatch:

jobs:
  call-fetch-data:
    uses: ./.github/workflows/fetch-data-and-push.yml
    with:
      sources: >
        gatewaytheatre,
        kaymeekcentre,
        terrabrucemajestic,
        factorytheatre,
        rotarycentreforthearts,
        rcmusic,
        bardonthebeach,
        sidwilliams
    secrets:
      publisher-uri: ${{ secrets.PUBLISHER_URI_GREGORY }}