name: Main

on:
    workflow_dispatch:

jobs:
  call-get-data:
    strategy:
        matrix:
          url:
            - 'https://system.spektrix.com/gatewaytheatre/api/v3/events'
            - 'https://system.spektrix.com/kaymeekcentre/api/v3/events'
            - 'https://system.spektrix.com/terrabrucemajestic/api/v3/events'
    uses: ./.github/workflows/fetch-data-and-push.yml
    with:
      api-url: ${{ matrix.url }}
    secrets:
        publisher-uri: ${{secrets.PUBLISHER_URI_GREGORY}}
